### PR TITLE
Added support to WebView onMessage()

### PR DESCRIPTION
**Pull request by angelstoone**
Hi everyone, I truly need this feature so I have basically continued what was done in the current PR #81 with the right naming that's it.

### CODE REVIEW

**Comment by lucasferreira** [comment]
Hi @angelstoone 

Thanks for this good contribution. But, in README sample I think there is a typo:

`injectedJavaScript={this.getJavascript()}`

I think that by your sample method correct it's:

`injectedJavaScript={this.javascriptToInject()}`

What do you think?

**Comment by angelstoone** [comment]
Hi @lucasferreira,

You are right!!! I have just updated it 👍 

Let me know if that's ok 😉

BTW thanks for this really good package.

**Comment by angelstoone** [comment]
Thanks, @lucasferreira. Could you please test if the changes that I have done in the .gitignore file do not break anything, please?

**Comment by lucasferreira** [comment]
Hi @angelstoone 

I had never used `.npmignore` file before, but you changes in `.gitignore` seems fine to me.

Thanks for this contribution again ;)

**Comment by angelstoone** [comment]
The same goes for me. But when I have used npm instead of yarn to install the package, it seemed to me that npm generate the .npmignore file that basically was the .gitignore file. And given that I have added the node_modules in my .gitignore file when using npm to install the package it was not adding the node_modules causing an error that was not easy to spot.
If you need it, you can check [this](https://stackoverflow.com/questions/24942161/does-npm-ignore-files-listed-in-gitignore) discussion about it on **StackOverflow**.

**Comment by lucasferreira** [comment]
Hi @angelstoone,

I don't get you problem, but accord to your suggestion: https://stackoverflow.com/a/24942436 only the .gitignore file will do the work if the two files (.npmignore and .gitignore) will have the same content (IMHO that's de case).

**Comment by angelstoone** [comment]
I think that the `.npmignore` should be almost the same apart from the `node_modules/` entry because we need the other package dependencies in order to make `react-native-webview-android` works. Basically, I think that we should add the following `.npmignore` file:

```
*.class

# OSX
#
.DS_Store

# node.js
#
# node_modules/
npm-debug.log
yarn-error.log

# Android/IntelliJ
#
build/
.idea
.gradle
local.properties
*.iml

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.ear

# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
hs_err_pid*
```
Just to let the node_modules to be installed. What do you think? You can easily try it anyway by installing the current package version on `master` and see if we really need this change to be done.

**Comment by lucasferreira** [comment]
Can we research in others _coolers_ packages around?

If we look into this module: https://github.com/react-community/react-native-image-picker
That's the `.gitignore`: https://github.com/react-community/react-native-image-picker/blob/develop/.gitignore
And that's the `.npmignore`: https://github.com/react-community/react-native-image-picker/blob/develop/.npmignore

They are different, but both of then had the `node_modules` ignored.

**Comment by angelstoone** [comment]
Ok @lucasferreira, we should be fine then 😉

**Pull request merged**
