### PR TITLE
js call app

### PR DESCRIPTION
**Pull request by HancleLee**
now js can call app;

Usage:
<!DOCTYPE html>
<html lang="en" xmlns:height="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <title>Carson</title>
    <script>
        function jsToApp(){
            try {
                  window.app.jsToApp("hello,app!!!");
            } catch(e) {
                 console.log("js to app erro");
            }
        }
    </script>
</head>
<body>
<button type="button" id="button1" onclick="jsToApp()" >try to click me </button>
</body>
</html>

<WebViewAndroid
              javaScriptEnabled={true}
              domStorageEnabled={true}
              scalesPageToFit={true}
              startInLoadingState={true}
              geolocationEnabled={false}
              builtInZoomControls={false}
              decelerationRate="normal"
              automaticallyAdjustContentInsets={false}
              url={url}
              style={styles.base}
              jsToApp={this._jsToApp.bind(this)}
          />

_jsToApp(params) {
      // alert("_jsToApp");
    }

### CODE REVIEW

**Comment by lucasferreira** [comment]
Hi @HancleLee 

Could you write some sort of README instruction for use this new feature?

**Comment by HancleLee** [comment]
Hi @lucasferreira 
Can you merge it if not any problem here?

**Comment by lucasferreira** [comment]
Hi @HancleLee,

Thanks again for your contribution. What do you think about we adopt the same method/api style of native RN WebView?

https://facebook.github.io/react-native/docs/webview.html#onmessage

The native webview uses `onMessage` on app side to receive data from webpages...

**Comment by lucasferreira** [comment]
Closed in favor of #91

**Pull request closed without merging**
