### PR TITLE
Add support for stopLoading, postMessage, injectJavascript

### PR DESCRIPTION
**Pull request by andriichernenko**

### CODE REVIEW

**Comment by lucasferreira** [comment]
Hi @andriichernenko 

Thanks for this, could you write some sort of usage / sample in README?

**Comment by andriichernenko** [comment]
@lucasferreira Done!

**Comment by andriichernenko** [comment]
@lucasferreira Sorry for bothering you, could you please merge/release this sometime soon?

**Comment by vitalikzyzych** [comment]
@andriichernenko Thanks for this PR.
@lucasferreira Appreciating PR merge/release soon

**Comment by lucasferreira** [comment]
Thanks @andriichernenko !

Hi @vitalikzyzych it's already released.

**Pull request merged**
